apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: url-based-api-vehicle-search
  description: URL based API vehicle search
  annotations:
    openapi/ref-basepath: https://github.com/RoadieHQ/backstage-openapi-ref-example/tree/main/url/spec
spec:
  type: openapi
  lifecycle: production
  owner: vehicle-search-team
  definition:
    $text: ./spec/openapi.yaml
