openapi: 3.0.0
info:
  title: Vehicle Search
  description: |
    The Vehicle search API
  version: 1.0.0-Draft
tags:
  - name: Vehicle Search
    description: APIs to query vehicle properties and vehicle model.
servers:
  - url: test@example.com
paths:
  /vehicles/brands:
    get:
      summary: Lists all available brands
      operationId: vehicleBrands
      responses:
        "200":
          description: Returns the list of brands
        "500":
          $ref: "https://raw.githubusercontent.com/RoadieHQ/backstage-openapi-ref-example/main/url/spec/models.yaml#/components/responses/ServerError"
      tags:
        - Vehicle Search
